# system configuration  oss-type: 'aliyun'    # 控制oss选择走本期还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: 'mysql'
  use-multipoint: false


# mysql connect configuration
mysql:
  hostname: 'localhost'
  port: 3306
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'db-test'
  username: 'test-username'
  password: '000000'
  max-idle-cons: 10
  max-open-cons: 100
  log-mode: true
  log-zap: ""


# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[rights-log]'
  director: 'logs'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''
